### ISSUE TITLE
How to add more than 5 sentences in Experience segment

### ISSUE THREAD

**Issue by itsmemohan** [aamay001/react-resume#111]
Hi Team, 
I did check the list of closed issues and please correct me if I am wrong, While adding data into the code-editor in json format , regarding the experience section , "impact1" -"impact5" - i.e it allows only to show 5 sentences and if I add "impact6", the data is not visible in the resume. 
Please advise. 
Thanks for your support in advance.

Honestly, I liked this tool which creates the resume in a beautiful format. Thanks to the entire team.

**Comment by aamay001** [comment]
@itsmemohan The `impact#` properties are static. This is by design. 

Please see https://github.com/aamay001/react-resume/blob/6236e8a48571fa619f6aa527e70c70522ad60d36/src/components/Resume/Experience.js#L27 for ref.

**Comment by aamay001** [comment]
@itsmemohan if you have a need to support more than 5, feel free to submit a PR with an update.
