### ISSUE TITLE
Update Readme.MD

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#28]
Document usage instructions.

**Comment by MaisaMilena** [comment]
I worked on it [here](https://github.com/aamay001/react-resume/pull/49)

**Comment by osmarpetry** [comment]
@aamay001 can you be more clear about what do you want?

**Comment by aamay001** [comment]
> @aamay001 can you be more clear about what do you want?

Sorry for not being clear. What I mean is document how the application works for the user. Technical documentation not required at this time.

**Comment by MaisaMilena** [comment]
@aamay001 you meant adding info about how to change fonts, input info and things like that? Because I think these things are quite intuitive when looking at the website and try it. I changed some things related to the organization of the README to make the info cleaner.

**Comment by aamay001** [comment]
> @aamay001 you meant adding info about how to change fonts, input info and things like that? Because I think these things are quite intuitive when looking at the website and try it. I changed some things related to the organization of the README to make the info cleaner.

Again, I apologize for not being clear. It would be nice to document the structure of the JSON document. For example, some items become links if there is a link provided. Another one is, event thought the Tech Skills property is an array of objects, it really only supports two items.

**Comment by aamay001** [comment]
Contributors snippet from here `https://contributors-img.firebaseapp.com/`

**Comment by MaisaMilena** [comment]
> @MaisaMilena If you don't mind, as you work on this please add this snippet so we can start to show the list of contributors:
> 
> `<a href="https://github.com/aamay001/react-resume/graphs/contributors"> <img src="https://contributors-img.firebaseapp.com/image?repo=aamay001/react-resume" /> </a>`
> 
> Thanks again for your contributions!

@paulywill kindly did this on his [PR](https://github.com/aamay001/react-resume/pull/56)
