### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#31]
Add a toggle switch for a dark mode.

**Comment by ram-nad** [comment]
Sir, I would like to work on this.

**Comment by aamay001** [comment]
> Sir, I would like to work on this.

Go for it. Thanks!

**Comment by ram-nad** [comment]
![Screenshot_20191005_110021](https://user-images.githubusercontent.com/44163356/66250369-6857ba80-e75f-11e9-9fb3-3f84d6e0cd72.png)

Sir is this color combination good?

**Comment by ram-nad** [comment]
Haven't changed icon colours yet. Would change it when colour scheme is finalised.

**Comment by aamay001** [comment]
Yes, this looks awesome! Just a note, when printing the color scheme should be back to standard printing colors. Let me know if you need more detail about this.

**Comment by ram-nad** [comment]
Sir does this mean that when printing then we must always use the default colours?

**Comment by aamay001** [comment]
> Sir does this mean that when printing then we must always use the default colours?

Yes, this can be accomplished with a media query for printing.
