### ISSUE TITLE
Add `visible` prop to each entry

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#40]
This feature would the ability to store multiple entries in each section with the ability to only display the ones needed for a version of the resume.

**Comment by jasoncoryalvernaz** [comment]
My thought on this was to add an `isVisible` boolean field to each entry in the JSON file. Then simply check that field when iterating over the entries. How does that sound to you?

**Comment by aamay001** [comment]
> My thought on this was to add an `isVisible` boolean field to each entry in the JSON file. Then simply check that field when iterating over the entries. How does that sound to you?

That's exactly what I had in mind.

**Comment by jasoncoryalvernaz** [comment]
Cool. Added in pull request #41. Awesome app by the way. I'll definitely be using this.
