### ISSUE TITLE
Refactor the Technical Skills Section

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#70]
Refactor the Technical Skills Section

Use `display: flex`
Allow Custom Categories
Allow the user to configure `flex-basis` for each category. (Default is 50% if not defined)

https://github.com/aamay001/react-resume/blob/e380027f83b15d5006450d9c49ea1a3436089370/src/components/Resume/TechnicalSkills.js#L12

**Comment by ruhci28** [comment]
Hii @aamay001  i want to work on this can you give some more details

**Comment by aamay001** [comment]
> Hii @aamay001 i want to work on this can you give some more details

I've already assigned it. I will add more issues soon. Stay tuned.

**Comment by ruhci28** [comment]
sure
