### ISSUE TITLE
Integrate JSON Resume Schema

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#72]
Make all necessary changes to integrate the JSON resume schema.

https://jsonresume.org/schema/

This should be broken out into different PRs. One PR per section in the schema.

One PR per section.

1. basics - @Mr-emeka
2. work - @harshilparmar
3. volunteer
4. education
5. awards
6. publications
7. skills
8. languages
9. interests
10. references

**Acceptance Criteria**
1. Fill in the corresponding method in [`src\helpers\migration.helper.js`](https://github.com/aamay001/react-resume/blob/development/src/helpers/migration.helper.js)
2. Update [`src\migratedresume-data.js`](https://github.com/aamay001/react-resume/blob/development/src/migratedresume-data.js) - You should edit the section you are working on by changing the property value to the new corresponding value using the jsonresume schema.
3. Update the corresponding React Component under [`src\components\Resume`](https://github.com/aamay001/react-resume/blob/development/src/components/Resume)
4. Update [`src\helpers\resume.helper.js`](https://github.com/aamay001/react-resume/blob/development/src/helpers/resume.helper.js) as needed.
5. Do not add additional HTML to support new schema properties that are currently not supported.
6. Some sections have extended properties like `isVisible` that is managed by the [MoreVisibilityModal](https://github.com/aamay001/react-resume/blob/development/src/components/Tools/MoreVisibilityModal.js). Retain the `isVisible` property where defined.
7. Submit PR to `development` branch
8. Do not commit white space changes to files without code changes.

**You do not need to add components to support the sections that are not currently rendered. If a section already contains a rendered component, update the component to use the updated property names. New issues will be created for sections that need a component for rendering.**

**I will update this post with assignments as each section is assigned.** 

**Do not add additional HTML to support new schema properties that are currently not supported (i.e. `basics.picture` and `basics.label`). New issues will be created for these changes.**

**YOUR PRs SHOULD GO TO the `development` branch**

**Comment by Mr-emeka** [comment]
would like to work on this @aamay001

**Comment by aamay001** [comment]
> would like to work on this @aamay001

Which section are you going to work on?

**Comment by Mr-emeka** [comment]
basics @aamay001

**Comment by harshilparmar** [comment]
I would like to work on Work section 😃

**Comment by aamay001** [comment]
> I would like to work on Work section 😃

Go for it! 👍

**Comment by aamay001** [comment]
> @aamay001 Brother as I understand,I have to change old data with new https://jsonresume.org/schema/ data.
> For that I have few questions.
> 
> 1. Is I have to call that data via api and integrate with react? if yes how ? What is endpoint?
> 2. And what the purpose of migration helper file ?
> 
> Thanks,Correct me If I am wrong.I simply want to understand flow of this feature 🙇

Hi @harshilparmar, the task is to swap the current resume scheme with the json resume schema. Essentially, you are to complete the function for the work section in `src\helpers\migration.helper.js` and then update the corresponding React components. Please let me know if you need more detail and we can work something out.

To answer your two questions: 1.) No, there is no need to call any API. 2.) The migration helper will be used to convert any existing resumes to the new format. This will ensure that we can migrate existing users to the new schema when they visit the application after the update has happened.

**Comment by harshilparmar** [comment]
@aamay001 Thanks brother 💯

**Comment by harshilparmar** [comment]
@aamay001  Brother, I have understood that I simply have to write code to convert old json to new json schema.
Here I have another question
In old resume data there are this type of objects in an array
```
{
city: "City",
company: "Experience 1",
dateFrom: "XX/XXXX",
dateTo: "",
impact1: "Something awesome you did 1.",
impact2: "Something awesome you did 2.",
impact3: "",
impact4: "",
isVisible: true,
position: "Position 1",
primaryWorkBrief: "Brief description of your main tasks."
state: "CA"
} 
```
And for new resume data object looks like this
```
{
    "company": "Company",
    "position": "President",
    "website": "http://company.com",
    "startDate": "2013-01-01",
    "endDate": "2014-01-01",
    "summary": "Description...",
    "highlights": [
      "Started the company"
    ]
}
```
There are some common fields like company,position,startDate as dateTo,endDate as dateFrom.
My question is what to do for website,summary and highlights ? Is highlights will show impact properties and summary for primaryWorkBrief ?

Thanks!!
You have made a great project 🎉

**Comment by aamay001** [comment]
@harshilparmar thanks for checking with me. Yes, all `impactX` properties will now be inside of the `highlights` array. `primaryWorkBrief` should become `summary`. `city` and `state` can be appended to the end of the summary.

`website` is a new property. Just include in the new schema but it is not necessary to update the react component to render this property at this time. 

Thanks

**Comment by Mr-emeka** [comment]
@aamay001 sorry I'm just checking in with you.
After filling up the corresponding method for _**basics**_ and Updating src\helpers\resume.helper.js as needed.
My Question is?
where do I use the migration method? 
cause data passed into the initial state of redux happens to be the old JSON schema.

**Comment by aamay001** [comment]
@Mr-emeka  Please see my response [above](https://github.com/aamay001/react-resume/issues/72#issuecomment-706391010) to another contributor 

https://github.com/aamay001/react-resume/issues/72#issuecomment-706391010
