### ISSUE TITLE
DownloadButton: Add Cypress Test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#77]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/Buttons/DownloadButton.js#L5

Test the behavior using Cypress.

##Acceptance Criteria

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration`

**Comment by jespicas** [comment]
Hi,
I see some PR created to add some Cypress tests, but I don't see a task to execute a Cypress Tests.
How you expect execute all test with Cypress in this project ??

**Comment by aamay001** [comment]
Hi @jespicas, please make sure you are working from the `development` branch. There are two scripts in the [package.json](https://github.com/aamay001/react-resume/blob/6378b15bb9149b44d97f6daf1f37c85de801eaab/package.json#L30) to run the Cypress tests.

**Comment by aamay001** [comment]
@jespicas I assigned you this issue but you actually did not ask for it. Do you want to work on this? If not I will remove the assignment.

**Comment by jespicas** [comment]
I can try to do

**Comment by jespicas** [comment]
This PR contains the test https://github.com/aamay001/react-resume/pull/102

**Comment by aamay001** [comment]
Changes requested. Please see PR #102

**Comment by aamay001** [comment]
Thanks for your contributions!
