### ISSUE TITLE
EditorButton: Add Cypress Test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#78]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/Buttons/EditorButton.js#L6

Test the behavior using Cypress.

##Acceptance Criteria

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration`

**Comment by jespicas** [comment]
The PullRequest it's created
https://github.com/aamay001/react-resume/pull/92
