### ISSUE TITLE
ItemToggleButton: Add Cypress Test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#79]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/Buttons/ItemToggleButton.js#L5

Test the behavior using Cypress.

##Acceptance Criteria

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration`

**Comment by PhilippeBarre** [comment]
Hello, I will help you to test all the toggle buttons 👍

**Comment by aamay001** [comment]
Thank you @PhilippeBarre, I will review your PR.

**Comment by aamay001** [comment]
Thank you for your contributions!
