### ISSUE TITLE
LocalStorageToggle: Add Cypress test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#81]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/Buttons/LocalStorageToggle.js#L15

Test the behavior using Cypress.

**Acceptance Criteria**

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration` if missing

**Comment by saw-jan** [comment]
@aamay001 I will make a PR on it

**Comment by aamay001** [comment]
Thanks for your contributions.
