### ISSUE TITLE
MoreVisibilityButton: Add Cypress test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#82]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/Buttons/MoreVisibilityButton.js#L7

Test the behavior using Cypress.

**Acceptance Criteria**

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration` if missing

**Comment by jessie-codes** [comment]
I can take a look at this one. I should have a PR up shortly.

**Comment by aamay001** [comment]
Thank you for your contribution.
