### ISSUE TITLE
PrintButton: Add Cypress test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#83]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/Buttons/PrintButton.js#L5

Test the behavior using Cypress.

**Acceptance Criteria**

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration` if missing

**Comment by raibove** [comment]
Can I try working on this issue.

**Comment by aamay001** [comment]
It's yours.

**Comment by raibove** [comment]
Sorry 
I tried but I am not able to write the test. I don't know cypress.
Shall I unassign myself?

**Comment by aamay001** [comment]
No problem thanks for trying.

**Comment by harshilparmar** [comment]
@aamay001 Can I try this brother.

**Comment by aamay001** [comment]
Go for it.
