### ISSUE TITLE
SaveToCloudButton: Add Cypress test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#84]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/Buttons/SaveToCloudButtons.js#L31

Test the behavior using Cypress.

**Acceptance Criteria**

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration` if missing

**Comment by jespicas** [comment]
Hi,
I started to create this test.
But .. I have an error try to click on any Cloud Storage ( Dropbox, OneDrive or Driver) 
I give an error preparing file, what I'm doing wrong ?

**Comment by aamay001** [comment]
This is because there are two environment variables in the `.env` that need to be populated. I can send you some temporary secrets via email. Can you please send me an email so I know where to send you the temporary secrets? You can use the email on my profile.

**Comment by jespicas** [comment]
PullRequest ready https://github.com/aamay001/react-resume/pull/101

**Comment by aamay001** [comment]
@jespicas changes requested. Please see PR #101 .

**Comment by aamay001** [comment]
Your test was timing out because the Azure function can take up to 30 seconds to cold start. I updated the test to have a longer timeout and verified that all tests were passing. Thanks for your contribution.
