### ISSUE TITLE
CodeEditor: Add Cypress test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#85]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/CodeEditor.js#L21

Test the behavior using Cypress.

**Acceptance Criteria**

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration` if missing

**Comment by PhilippeBarre** [comment]
Hello,

I will try to do it 

Best regards

**Comment by aamay001** [comment]
Thanks for your contributions!
