### ISSUE TITLE
FontSelector: Add Cypress test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#86]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/FontSelector.js#L9

Test the behavior using Cypress.

**Acceptance Criteria**

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration` if missing

**Comment by Rocksheep** [comment]
I'll help you out! Please assign this task to me.

**Comment by aamay001** [comment]
It's yours, thanks for your help!

**Comment by aamay001** [comment]
Resolved by #88
