### ISSUE TITLE
MoreVisibilityModal: Add Cypress test

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#87]
https://github.com/aamay001/react-resume/blob/4bfa50523655d76fb7c373f829fb4bef9e05e436/src/components/Tools/MoreVisibilityModal.js#L31

Test the behavior using Cypress.

**Acceptance Criteria**

1. Submit PR to the development branch
2. Create folder structure to match src tree under `cypress\integration` if missing

**Comment by harshilparmar** [comment]
@aamay001 Can I try this? You have to do e2e test right? Only for MoreVisibilityModal ??

**Comment by aamay001** [comment]
Yes, you can test for DOM change behavior and data changes in the resume data. This will toggle the `isVisible` prop for the items that support it.

**Comment by harshilparmar** [comment]
@aamay001 ok got it !! I will let you know 👍

**Comment by harshilparmar** [comment]
@aamay001 hello, is this already done in

https://github.com/aamay001/react-resume/pull/90 ??

**Comment by aamay001** [comment]
Yes, it is @harshilparmar. Sorry about that. Closing this issue now.

**Comment by harshilparmar** [comment]
> Yes, it is @harshilparmar. Sorry about that. Closing this issue now.

Any other issue that I can solve?
